### ISSUE TITLE
It doesn't make toast.

### ISSUE THREAD

**Issue by andrewsentman** [andrewsentman/sharedProject#5]
When I found this project, I was looking for an all-in-one software solution for all of my everyday needs. While it can do my homework, walk my dog, and even drive me to school, I was disappointed to find out when I gave it a slice of bread, it failed to brown and crisp. In fact, it became soggy in reaction to my tears of despair at the apparent lack of toast.

**Comment by ThePatrickBrady** [comment]
that is funny
