### ISSUE TITLE
Coffee error

### ISSUE THREAD

**Issue by chordtoll** [andrewsentman/sharedProject#7]
This software claims to be HTCPCP/1.0 compliant, but when I send a BREW request, instead of receiving coffee, I receive a HTCPCP 418 error. Please fix this as soon as possible, I need my coffee to stay awake at work.

**Comment by andrewsentman** [comment]
HTCPCP 418 indicates that the server is a teapot (see [RFC 2324](http://tools.ietf.org/html/rfc2324)). Since teapots cannot make coffee, the BREW method is not valid. What device is the software running on?

**Comment by andrewsentman** [comment]
I am using a teapot 9000. ![Image of teapot 9000](http://i1.wp.com/www.qdh.org.uk/wordpress/wp-content/uploads/2014/05/teasmade.png?resize=320%2C300)
What do I need to do to make coffee with it?

**Comment by chordtoll** [comment]
I am using a teapot 9000:
![Image of teapot 9000](http://i1.wp.com/www.qdh.org.uk/wordpress/wp-content/uploads/2014/05/teasmade.png?resize=320%2C300)
What do I need to do to get it to make coffee?

**Comment by andrewsentman** [comment]
Sorry, but we don't plan to support teapots at this time. We recommend you purchase a coffeepot.

**Comment by FirePieman** [comment]
pls

**Comment by andrewsentman** [comment]
Since the teapot 9000 is not a coffee pot, it does not support coffee. We suggest you buy a coffee pot.
